apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: droidian-client
  name: droidian-client
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: droidian-client
  strategy:
    rollingUpdate:
      maxSurge: 100
      maxUnavailable: 50
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: droidian-client
    spec:
      containers:
        - image: localhost:5000/droidian/droidian-client:latest
          imagePullPolicy: Always
          name: droidian-client
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
