apiVersion: v1
kind: Service
metadata:
  name: droidian-client-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: droidian-client
  ports:
    - name: http
      port: 80
      targetPort: 80
